const merge = require('webpack-merge');
const common = require('./webpack.common.js');
const TerserJSPlugin = require('terser-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const CreateFilePlugin = require('create-file-webpack');

module.exports = merge(common, {
    mode: 'production',
    optimization: {
        minimizer: [new TerserJSPlugin({}), new OptimizeCSSAssetsPlugin({})],
    },
    plugins: [
        new CleanWebpackPlugin(),
        new MiniCssExtractPlugin({
            filename: '[name].[hash].css',
            chunkFilename: '[id].[hash].css',
        }),
        new CopyWebpackPlugin([{
            from: 'src/static',
        }]),
        new CreateFilePlugin({
            path: './docs',
            fileName: 'README.txt',
            content: 'Do not commit anything in the `docs`-folder. This folder is auto-generated by `npm run build`. If you want to commit a static file, do so in the `src/static`-folder.'
        })
    ],
    module: {
        rules: [{
            test: /\.(sa|sc|c)ss$/i,
            use: [
                {
                    loader: MiniCssExtractPlugin.loader,
                    options: {
                        hmr: false
                    }
                },
                'css-loader',
                'sass-loader',
            ]
        }]
    },
});