identifier: k6wcg120nfh6d4r8
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: sebastianwie-land
homeFolder: C:\Users\micro\Workspaces\sebastianwie.land
distFolder: dist/sebastianwie-land
outDir: C:\Users\micro\Workspaces\sebastianwie.land\dist\static
handle404: ''
allowErrorCollect: true
