import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormArray, FormBuilder, Validators } from '@angular/forms';
import { Store } from '@ngrx/store';
import { debounceTime, map, mergeMap, Subject, take, takeUntil } from 'rxjs';
import { Message } from '../../interfaces/message';
import { MultipartDocumentService } from '../../services/multipart-document.service';
import { OpenpgpService } from '../../services/openpgp.service';
import { reset, storeInputs } from '../../store/actions/contact-form.actions';
import { getContactFormInputs } from '../../store/selectors/contact-form.selectors';

@Component({
  selector: 'nwie-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss']
})
export class ContactComponent implements OnInit, OnDestroy {
  public contactForm = this.fb.group({
    subject: ['', Validators.required],
    fromName: ['', Validators.required],
    fromEmail: ['', [Validators.email, Validators.required]],
    message: ['', Validators.required],
    attachments: this.createAttachmentsArray(),
  });

  public attachmentFields!: FormArray;

  private destroy$ = new Subject<void>();

  constructor(
    private fb: FormBuilder,
    private store: Store,
    private openpgpService: OpenpgpService,
    private multipartDocumentService: MultipartDocumentService,
  ) { }

  ngOnInit(): void {
    this.listenToChanges();

    this.store.select(getContactFormInputs)
      .pipe(
        take(1)
      )
      .subscribe(values => {
        this.contactForm.setValue({ ...values, attachments: [null] });
      });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.unsubscribe();
  }

  private createAttachmentsArray(): FormArray {
    this.attachmentFields = this.fb.array([
      [null],
    ]);
    return this.attachmentFields;
  }

  public addAttachmentField(): void {
    this.attachmentFields.push(this.fb.control(null));
  }

  public deleteAttachment(index: number): void {
    this.attachmentFields.removeAt(index);
  }

  private listenToChanges(): void {
    this.contactForm.valueChanges
      .pipe(
        takeUntil(this.destroy$),
        debounceTime(300)
      )
      .subscribe((val: Message) => {
        this.store.dispatch(storeInputs({
          subject: val.subject,
          fromName: val.fromName,
          fromEmail: val.fromEmail,
          message: val.message
        }));
      });
  }

  public reset(): void {
    this.contactForm.setControl('attachments', this.createAttachmentsArray());
  }

  public onSubmit(): void {
    this.multipartDocumentService.createMultipartDocument(this.contactForm.value)
      .pipe(
        mergeMap(document => this.openpgpService.encrypt(document.toString()))
      )
      .subscribe(encrypted => {
        console.log(encrypted);
      });

    // console.log(this.contactForm.value);
    // const multipartDocument = this.multipartDocumentService.multipartDocumentFactory()
    //   .setContentType('multipart/mixed')
    //   .useAutoGeneratedBoundary()
    //   .addPart(
    //     this.multipartDocumentService.mimeDocumentFactory()
    //       .setPlainTextContent(this.contactForm.value.message)
    //       .build()
    //   )
    //   .build();

    // console.log(multipartDocument.toString());

    // this.openpgpService.encrypt(multipartDocument.toString()).subscribe(encrypted => {
    //   console.log(encrypted);
    // });
  }
}
